version: "3"

services:

  frontend:
      image: frontend:latest
      ports:
        - 3001:3000
      volumes:
        - ./:/usr/src/app
      command: npm start
      tty: true
      stdin_open: true

  app:
    image: wefoxgroup/wg-web-challenge:latest
    container_name: wg-web-challenge
    ports:
      - 3000:3000
