version: '3.4'

services:
  babeltypes:
    image: babeltypes
    build:
      context: node_modules/@babel/types
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
