export class PostClass {
  // id is optional because its an autogenerated field that the user doesn't set, so when we are
  // creating a new post we need to be able to instantiate a PostClass without passing an id
  id: number = -1;
  title: string = "";
  content: string = "";
  lat: string = "";
  long: string = "";
  image_url: string = "";
  created_at: string = "";
  updated_at: string = "";

  constructor(
    title: string,
    content: string,
    lat: string,
    long: string,
    image_url: string,
    created_at: string,
    updated_at: string
  ) {
    this.title = title;
    this.content = content;
    this.lat = lat;
    this.long = long;
    this.image_url = image_url;
    this.created_at = created_at;
    this.updated_at = updated_at;
  }
}
